export const projects = [
  {
    slug: 'nci-crm', n: '01', title: 'NCI CRM', category: 'Internal CRM · National Cancer Institute',
    desc: 'An internal CRM for the National Cancer Institute, with role-based access, responsive forms and API integration.',
    tags: ['Angular', 'Tailwind CSS', 'Role-based Access', 'API Integration'], tone: 'nci', preview: 'Internal CRM workspace',
    context: 'Internal teams needed a clear CRM interface that respected user roles while keeping everyday data entry straightforward.',
    contribution: 'Built the Angular and Tailwind CSS frontend, created role-based permissions, and developed responsive forms connected to project APIs.',
    outcome: 'Delivered a structured internal workspace designed to make access, form completion and daily CRM workflows easier to manage.',
  },
  {
    slug: 'trr-admin-system', n: '02', title: 'TRR Admin System', category: 'Admin Platform · Thai Roong Ruang Group',
    desc: 'An admin platform for Thai Roong Ruang Group with dashboards, calendars, data tables, forms and location mapping.',
    tags: ['Angular', 'Tailwind CSS', 'Dashboards', 'Maps'], tone: 'trr', preview: 'Admin dashboard',
    context: 'Operational data needed to be easier to review, update and understand across dashboards, schedules and location-based information.',
    contribution: 'Developed the Angular frontend with dashboard charts, calendars, forms, data tables and map views generated from latitude and longitude.',
    outcome: 'Created an admin experience that brings essential management tools and information into one responsive interface.',
  },
  {
    slug: 'sos-wasty', n: '03', title: 'SOS Wasty', category: 'CRM & LINE LIFF · Ascend Co., Ltd.',
    desc: 'A responsive CRM and LINE LIFF experience designed for smooth, API-connected workflows.',
    tags: ['Next.js', 'Tailwind CSS', 'Ant Design', 'LINE LIFF'], tone: 'sos', preview: 'CRM and LINE LIFF',
    context: 'CRM workflows needed a responsive interface that could work naturally within the LINE ecosystem and stay connected to project APIs.',
    contribution: 'Built the frontend with Next.js, Tailwind CSS and Ant Design, then integrated API-driven experiences for the CRM and LINE LIFF flows.',
    outcome: 'Delivered a polished, responsive experience that supports customer-facing and operational interactions across devices.',
  },
  {
    slug: 'ldb-pro', n: '04', title: 'LDB Pro', category: 'Event workflow · Witsawa Corporation',
    desc: 'A custom QR code scanning module that streamlines event participation for doctors and pharmacists.',
    tags: ['QR Code', 'Web Application', 'Workflow Tool'], tone: 'ldb', preview: 'QR check-in flow',
    context: 'Event participation required a faster, clearer check-in process for doctors and pharmacists.',
    contribution: 'Built a custom QR code scanning module focused on making attendee verification simple and practical during the event flow.',
    outcome: 'Delivered a focused web workflow that helps teams manage event participation with less manual handling.',
  },
  {
    slug: 'cmdf', n: '05', title: 'CMDF', category: 'Product interface · Witsawa Corporation',
    desc: 'Turned design mockups into polished UI and connected Google Analytics 4 for product measurement.',
    tags: ['UI Implementation', 'Google Analytics 4', 'Product UI'], tone: 'cmdf', preview: 'Product interface',
    context: 'The product needed design mockups translated into a cohesive working interface, with measurement in place for future product decisions.',
    contribution: 'Implemented the supplied design direction as polished UI and connected Google Analytics 4 for product measurement.',
    outcome: 'Created a production-ready interface with a clearer path to understanding how people use the product.',
  },
  {
    slug: 'nfi-classwin', n: '06', title: 'NFI x Classwin', category: 'Website enhancement · Witsawa Corporation',
    desc: 'Improved an existing website by resolving issues and delivering new features for a better user experience.',
    tags: ['Web Enhancement', 'Feature Development', 'Bug Fixes'], tone: 'classwin', preview: 'Website enhancement',
    context: 'An established website needed targeted fixes and additions to better support its users and ongoing product needs.',
    contribution: 'Resolved existing issues and delivered new features while working within the constraints of an active website.',
    outcome: 'Improved the experience through practical enhancements that made the product more reliable and useful.',
  },
] as const;
